//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosGeoDevOps
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Auth
    {
        public int ID_Auth { get; set; }
        [Display(Name = "Логин")]
        public string Login { get; set; }
        [Display(Name = "Пароль")]
        public string Password { get; set; }
        public Nullable<int> ID_Sotrudnik { get; set; }
        public int ID_Role { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Role Role { get; set; }
    }
}
