//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosGeoDevOps
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reshenie
    {
        public int ID_Reshenie { get; set; }
        [Display(Name = "Номер решения")]
        public string Nom { get; set; }
        [Display(Name = "Описание")]
        public string Opis { get; set; }
        public int ID_Zapros { get; set; }
        public int ID_Sotrudnik { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Zapro Zapro { get; set; }
    }
}
