//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosGeoDevOps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RosGeoDevOpsEntities1 : DbContext
    {
        public RosGeoDevOpsEntities1()
            : base("name=RosGeoDevOpsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Mehanizm> Mehanizms { get; set; }
        public virtual DbSet<Reshenie> Reshenies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudniks { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Type_Test> Type_Test { get; set; }
        public virtual DbSet<Type_Zapros> Type_Zapros { get; set; }
        public virtual DbSet<Zapro> Zaproes { get; set; }
    }
}
