//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosGeoDevOps
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Auths = new HashSet<Auth>();
            this.Reshenies = new HashSet<Reshenie>();
            this.Zapros = new HashSet<Zapro>();
        }
    
        public int ID_Sotrudnik { get; set; }
        [Display(Name = "Фамилия")]
        public string Fam { get; set; }
        [Display(Name = "Имя")]
        public string Im { get; set; }
        [Display(Name = "Отчество")]
        public string Otch { get; set; }
        [Display(Name = "Серия")]
        public string Ser { get; set; }
        [Display(Name = "Номер")]
        public string Nom { get; set; }
        [Display(Name = "Почта сотрудника")]
        public string Mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth> Auths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reshenie> Reshenies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapro> Zapros { get; set; }
    }
}
