//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosGeoDevOps
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Zapros = new HashSet<Zapro>();
        }
    
        public int ID_Test { get; set; }
        [Display(Name = "Номер теста")]
        public string Nom { get; set; }
        [Display(Name = "Наименование теста")]
        public string Naim { get; set; }
        [Display(Name = "Результат")]
        public string Rezult { get; set; }
        public int ID_TypeTest { get; set; }
        public int ID_Mehanizm { get; set; }
        [Display(Name = "Дата тестирования")]
        public string DateTest { get; set; }
    
        public virtual Mehanizm Mehanizm { get; set; }
        public virtual Type_Test Type_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapro> Zapros { get; set; }
    }
}
